### ISSUE TITLE
Remove animation when going to mobile screen mode

### ISSUE THREAD

**Issue by lenmarbra** [lenmarbra/Online-Magazine---Self-Art#11]
Hi @gorazd

is there any way to remove the animation when changing screen mode to mobile? I mean, when using greenstock for the animation.

Br,
Maria

**Comment by gorazd** [comment]
Try looking at this thread:
https://greensock.com/forums/topic/21216-different-timeline-on-mobile/

**Comment by lenmarbra** [comment]
Thanks! This works!
